### ISSUE TITLE
Error: Unknown auth message code 10

### ISSUE THREAD

**Issue by CCCCCCCCCCCCCCCCCCCCCCCCCCCC33** [denodrivers/postgres#190] opened 2020-12-17 10:05 UTC
I have This Error When Connect To **PostgreSQL**

> error: Uncaught (in promise) Error: Unknown auth message code 10
>         throw new Error(`Unknown auth message code ${code}`);
>               ^
>     at Connection.handleAuth (connection.ts:197:15)
>     at Connection.startup (connection.ts:155:16)
>     at async Client.connect (client.ts:14:5)
>     at async main (db.ts:11:3)

**Comment by VaggelisKa** [comment] 2020-12-25 20:37
Hi im facing the same problem. Did you find a solution?

**Comment by MohammadAliChraghi** [comment] 2020-12-26 07:44
> Hi im facing the same problem. Did you find a solution?

No, I could not find it

**Comment by Soremwar** [comment] 2021-01-25 04:45
@CCCCCCCCCCCCCCCCCCCCCCCCCCCC33 See #182 and try the solutions listed there

Since this is quite probably an error related to postgres configuration rather than the library itself I'm going to close it. Feel free to open another issue if you can't reproduce with another postgres client

**Closed by Soremwar** 2021-01-25 04:45 UTC
