### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by winston0410** [denodrivers/postgres#416] opened 2022-12-01 19:33 UTC
When I have a table created like this:

```sh
CREATE TABLE IF NOT EXISTS foo (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
```

And when I select with the following code:

```typescript
		let connection!: PoolClient;
		try {
			connection = await pool.connect();

			const { rows } = await connection.queryObject<{
				id: string;
				created_at: string;
				updated_at: string;
			}>(`SELECT id, created_at, updated_at FROM foo;`);
		} finally {
			connection.release();
		}
```

I got the following error:

```sh
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at file:///Users/xxx/Desktop/foo/apps/deno/xys/src/routes/v1/rrule/+index.ts:38:29
    at async file:///xxx/hugosum/Desktop/foo/libs/deno/src/reno/file_router.ts:93:9
    at async https://deno.land/x/reno@v2.0.65/reno/router.ts:149:21
    at async Server.handler (file:///Users/xxx/Desktop/closesource/libs/deno/src/reno/file_router.ts:117:10)
    at async Server.#respond (https://deno.land/std@0.161.0/http/server.ts:301:18)
```

And seems like this will fix the issue, what do you think of including it in the source of `deno-postgres`?

https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-953187833

**Comment by Soremwar** [comment] 2022-12-01 19:49
`deno-postgres` has no issue serializing BigInt, and judging by your error it is likely being originated in the HTTP library you are using

I'm gonna close this, but if you have a reproducible test case I'll look into it

**Closed by Soremwar** 2022-12-01 19:49 UTC

**Comment by KaKi87** [comment] 2022-12-04 18:05
More specifically, like the error stack indicates, the issue is with `JSON.stringify`.

For example, `JSON.stringify(0n)` will output the same error.

So, if the value is lower or equal than `Number.MAX_SAFE_INTEGER` then `Number()` can be used, otherwise `.toString()` must be used.
