### ISSUE TITLE
Incompatible with Google Cloud Run: Device or Resource busy (os error 16)

### ISSUE THREAD

**Issue by asontha** [denodrivers/postgres#144] opened 2020-06-24 03:19 UTC
https://stackoverflow.com/questions/62504770/cloud-run-fail-to-connect-to-postgres-cloud-sql-device-or-resource-busy-os-err

Thoughts? Is this in this lib or is it perhaps something to do with deno?

**Comment by Soremwar** [comment] 2021-04-12 03:25
I overlooked this for a time sadly, however the missing feature required to support this is connection to Unix sockets, the next big thing in my radar

Closing this as duplicate of #149 because title is more clear there and can be understood as a feature request

**Closed by Soremwar** 2021-04-12 03:25 UTC
