### ISSUE TITLE
Environmental flag Disable logging

### ISSUE THREAD

**Issue by andreespirela** [denodrivers/postgres#279] opened 2021-04-20 23:41 UTC
There should be an environmental flag to disable logging.
![image](https://user-images.githubusercontent.com/60560109/115476708-6c97db80-a210-11eb-9dd5-13b2203498c0.png)

This is a blocker for Mandarine 3.0.0 release.

**Comment by Soremwar** [comment] 2021-04-20 23:57
It's in the milestone for 0.12.0, duplicate of #254

**Closed by Soremwar** 2021-04-20 23:57 UTC
